# Generated by Django 4.2.4 on 2023-08-31 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transaction_app', '0001_initial'),
        ('category_app', '0001_initial'),
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction', to='user_app.user'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='category',
            field=models.ManyToManyField(related_name='transaction', to='category_app.category'),
        ),
    ]
