# Generated by Django 4.2.4 on 2023-09-07 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.AlterField(
            model_name='user',
            name='annual_salary',
            field=models.BigIntegerField(default=50000),
        ),
        migrations.AlterField(
            model_name='user',
            name='bank_balance',
            field=models.BigIntegerField(default=50000),
        ),
    ]
