# Generated by Django 4.2.4 on 2023-09-07 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_remove_user_name_alter_user_annual_salary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='debt',
            field=models.BigIntegerField(default=0),
        ),
    ]
